kind: Deployment
apiVersion: apps/v1
metadata:
  name: ruby-hello-world
  namespace: cognite-test
  labels:
    app: ruby-hello-world
    app.kubernetes.io/component: ruby-hello-world
    app.kubernetes.io/instance: ruby-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: ruby-hello-world
  template:
    metadata:
      labels:
        deployment: ruby-hello-world
    spec:
      containers:
        - name: ruby-hello-world
          image: >-
            image-registry.openshift-image-registry.svc:5000/cognite-test/ruby-hello-world@sha256:ab0f64516d7827fbbc18b2f38683a5bbba6a5c6c3c57fe7e2f25fb15e8ce8fa0
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
